title: Site

columns:
  - width: 1/3
    sections:
      info:
        headline: Info
        type: info
        theme: white
        text: |
          Welcome to the Panel of Knowledge base! Here you can find all sites.

  - width: 2/3
    sections:
      pages:
        extends: sections/home/examples
        size: small
